### ISSUE TITLE
[validate] Allow profile to be the unique identifier from Data Package Schema Registry

### ISSUE THREAD

**Issue by zelima** [datahq/datahub-client#24]
Part of https://github.com/datahq/datahub-qa/issues/129

Currently, we await that `profile` property for datapackage may be URL or Path (or undefined) to the schema that the datapackage should be valid against. According to the [Frictionless data spec](https://frictionlessdata.io/specs/profiles/) the profile may be:
> It can be an id from the official [Data Package Schema Registry](https://frictionlessdata.io/schemas/registry.json), or, a fully-qualified URL that points directly to a JSON Schema that can be used to validate the profile

## Acceptance Criteria

* [ ] able to validate this dataset after `data get`: https://testing.datahub.io/core/ppp (Has profiled defined there) 
* [ ] able to set any desired url to schema
* [ ] able to set schema ID and validate so

## Tasks

* [ ] update code base

**Comment by zelima** [comment]
FIXED
